<a href="https://colab.research.google.com/github/jaskarannagi19/SampleGitRepo/blob/master/Copy_of_Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd #importing necessary libraries 
import os
import glob #too read files in block directory
from math import sqrt

In [6]:
info_dataframe = pd.read_csv('info.csv') #load household info to extract data into info dataframe

In [7]:
info_dataframe.head()   #look at first 5 rows of household file

       LCLid stdorToU    Acorn Acorn_grouped     file
0  MAC005492      ToU   ACORN-        ACORN-  block_0
1  MAC001074      ToU   ACORN-        ACORN-  block_0
2  MAC000002      Std  ACORN-A      Affluent  block_0
3  MAC003613      Std  ACORN-A      Affluent  block_0
4  MAC003597      Std  ACORN-A      Affluent  block_0

In [4]:
  #extract block.zip file using zip
! unzip block.zip -d block

Archive:  block.zip
replace block/block_0.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: block/block_0.csv
replace block/block_1.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [8]:
!ls

block  block.zip  info.csv  sample_data  test  test.zip

In [9]:
#............................read all files in block folder and combine them into1 dataframe....................................
file_path = "/block/"
df =  pd.DataFrame()
for filepath in glob.glob(os.path.join('block', '*.csv')):
  block_df = pd.read_csv(filepath)
  df= df.append(block_df)

In [10]:
df.describe()

               hh_0          hh_1  ...         hh_46         hh_47
count  56529.000000  56529.000000  ...  56529.000000  56529.000000
mean       0.314866      0.281767  ...      0.420778      0.362524
std        0.379846      0.349733  ...      0.469506      0.424128
min        0.000000      0.000000  ...      0.000000      0.000000
25%        0.101000      0.093000  ...      0.136000      0.115000
50%        0.183000      0.164000  ...      0.253000      0.212000
75%        0.351000      0.299000  ...      0.507000      0.418000
max        6.324000      6.721000  ...      6.086000      6.015000

[8 rows x 48 columns]

In [115]:
test_df = pd.merge(info_dataframe, df, on="LCLid")

In [116]:
#test_df.loc[test_df['LCLid'] == 'MAC000002']

In [117]:
#deleting stdorTou, file
del test_df['stdorToU']
del test_df['file']

In [118]:
#range of 6month or 2 months 1-05-2013 ---- 1-11-2013
test_df= test_df[(test_df['day']>'2013-05-01') & (test_df['day']<'2013-11-1')]

In [119]:
#Check for NaN ....remove that remove...print which removed

test_df.isnull().sum() #yay no NaNs found in 2 files I Used

LCLid            0
Acorn            0
Acorn_grouped    0
day              0
hh_0             0
hh_1             0
hh_2             0
hh_3             0
hh_4             0
hh_5             0
hh_6             0
hh_7             0
hh_8             0
hh_9             0
hh_10            0
hh_11            0
hh_12            0
hh_13            0
hh_14            0
hh_15            0
hh_16            0
hh_17            0
hh_18            0
hh_19            0
hh_20            0
hh_21            0
hh_22            0
hh_23            0
hh_24            0
hh_25            0
hh_26            0
hh_27            0
hh_28            0
hh_29            0
hh_30            0
hh_31            0
hh_32            0
hh_33            0
hh_34            0
hh_35            0
hh_36            0
hh_37            0
hh_38            0
hh_39            0
hh_40            0
hh_41            0
hh_42            0
hh_43            0
hh_44            0
hh_45            0
hh_46            0
hh_47            0
dtype: int64

In [120]:
#test_df.describe()

In [121]:
test_df.iloc[[0]]

         LCLid   Acorn Acorn_grouped         day  ...  hh_44  hh_45  hh_46  hh_47
248  MAC005492  ACORN-        ACORN-  2013-05-02  ...  0.241  0.167   0.17  0.263

[1 rows x 52 columns]

In [122]:
#KNN MODEL ON IT

#    Step 1: Calculate Euclidean Distance.
#    Step 2: Get Nearest Neighbors.
#    Step 3: Make Predictions.

In [123]:
# calculate the Euclidean distance between two vectors

In [124]:
test_df['Acorn_grouped']=pd.factorize(test_df['Acorn_grouped'])[0] + 0

In [125]:
#separate training and targets
X=test_df.iloc[:, 2:]
y = test_df.iloc[:, 1]


y=pd.factorize(y)[0] + 0

In [126]:

del X['day']

In [127]:
X

       Acorn_grouped   hh_0   hh_1   hh_2  ...  hh_44  hh_45  hh_46  hh_47
248                0  0.195  0.202  0.170  ...  0.241  0.167  0.170  0.263
249                0  0.188  0.125  0.092  ...  0.090  0.089  0.088  0.090
250                0  0.133  0.113  0.087  ...  0.107  0.131  0.101  0.089
251                0  0.090  0.086  0.089  ...  0.109  0.123  0.087  0.091
252                0  0.089  0.110  0.132  ...  0.129  0.130  0.092  0.087
...              ...    ...    ...    ...  ...    ...    ...    ...    ...
56424              1  0.093  0.085  0.108  ...  0.587  0.396  0.384  0.420
56425              1  0.304  0.128  0.130  ...  0.442  0.378  0.356  0.202
56426              1  0.129  0.133  0.132  ...  0.441  0.455  0.619  0.310
56427              1  0.399  0.362  0.266  ...  0.337  0.285  0.132  0.130
56428              1  0.102  0.092  0.092  ...  0.389  0.323  0.349  0.321

[18223 rows x 49 columns]

In [128]:
# Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
	distances = list()
	for train_row in train:
		dist = euclidean_distance(test_row, train_row)
		distances.append((train_row, dist))
	distances.sort(key=lambda tup: tup[1])
	neighbors = list()
	for i in range(num_neighbors):
		neighbors.append(distances[i][0])
	return neighbors
 
# Make a classification prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
	neighbors = get_neighbors(train, test_row, num_neighbors)
	output_values = [row[-1] for row in neighbors]
	prediction = max(set(output_values), key=output_values.count)
	return prediction

In [129]:
def euclidean_distance(row1,row2):
  distance =0.0
  for i in range(len(row1)-1):
    distance += (row1[i] - row2[i])**2
  return sqrt(distance)

In [130]:
cols = X.columns
X[cols] = X[cols].apply(pd.to_numeric, errors='coerce')

In [131]:
X = X.values.tolist()

In [132]:
prediction = predict_classification(X, X[200],3)

In [29]:
prediction

0.214

In [30]:
print('Expected %d, Got %d.' % (X[200][0], prediction))

Expected 1, Got 0.

In [133]:
file_path = "/test/"
df1 =  pd.DataFrame()
for file_path in glob.glob(os.path.join('block','*.csv')):
  block_df1= pd.read_csv(filepath)
  df1=df1.append(block_df1)

In [134]:
df1=df1.iloc[:,2:]

In [135]:
cols = df1.columns
df1[cols] = df1[cols].apply(pd.to_numeric, errors='coerce')

In [136]:
df1 = df1.values.tolist()

In [138]:
z= predict_classification(X, df1[0],3)

In [ ]:
for i in range(len(df1)):
  z =  predict_classification(X, df1[i],3)
  print(z)

0.867
0.78
0.179
0.242
0.317
0.195
0.6779999999999999
0.359
0.545
0.349
0.132
0.28800000000000003
0.08
0.317
0.599
0.128
0.298
0.113
0.231
0.073
0.132
0.212
0.244
0.147
0.175
0.191
0.133
0.122
0.257
0.8240000000000001
0.103
0.589
0.29
0.212
0.12
0.142
0.344
0.14
0.198
0.134
0.091
0.196
0.196
0.196
0.196
0.299
0.196
0.196
0.196
0.196
0.196
0.196
0.5710000000000001
0.585
0.304
0.335
0.121
0.141
0.294
0.177
0.232
0.21
0.234
0.343
0.317
0.181
0.426
0.41
0.217
0.138
0.457
0.16
0.16
0.316
0.16
0.16
0.377
0.588
0.175
0.927
0.354
0.147
0.8109999999999999
0.102
0.299
0.28300000000000003
0.131
0.165
0.14300000000000002
0.153
0.161
0.13
0.153
0.192
0.5
0.084
0.08800000000000001
0.589
0.16
0.332
0.8370000000000001
0.172
0.159
0.232
0.124
0.165
0.134
0.263
0.173
0.561
0.589
0.155
0.097
0.078
0.11
0.13699999999999998
0.08800000000000001
0.198
0.105
0.197
0.6990000000000001
0.603
0.16
0.187
0.131
0.317
0.425
0.157
0.212
0.133
0.46
0.457
0.244
0.157
0.78
0.387
0.113
0.443
0.6629999999999999
0.301
0.127
0.279
0.91
0.263
0.379
0.8220000000000001
0.285
0.343
0.282
0.482
0.338
0.632
0.312
0.6759999999999999
0.22
0.358
0.077
0.22
0.344
1.159
0.459
0.25
0.28800000000000003
0.285
0.336
0.237
0.42
0.285
0.322
0.71
0.261
0.335
0.355
0.197
0.197
0.18600000000000005
0.084
0.084
0.175
0.197
0.197
0.197
0.197
0.197
0.197
0.173
0.197
0.197
0.197
0.197
0.197
0.197
0.263
0.197
0.197
0.197
0.197
0.121
0.215
0.234
0.402
0.146
0.076
0.152
0.501
0.8109999999999999
0.117
0.212
0.35200000000000004
0.196
0.14
0.605
0.836
0.18
0.193
0.103
0.361
0.124
0.127
0.263
0.09
0.199
0.287

In [31]:
! unzip test.zip -d test

Archive:  test.zip
replace test/block_2.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: yes
  inflating: test/block_2.csv

In [32]:
file_path = "/test/"
df1 =  pd.DataFrame()
for file_path in glob.glob(os.path.join('block','*.csv')):
  block_df1= pd.read_csv(filepath)
  df1=df1.append(block_df1)

In [33]:
#separate training and targets
X=test_df.iloc[:, 2:]
y = test_df.iloc[:, 1]


y=pd.factorize(y)[0] + 0

In [34]:
#Decision Tree

In [35]:
import numpy as np


class Node:
    def __init__(self, predicted_class):
        self.predicted_class = predicted_class
        self.feature_index = 0
        self.threshold = 0
        self.left = None
        self.right = None


class DecisionTreeClassifier:
    def __init__(self, max_depth=None):
        self.max_depth = max_depth

    def fit(self, X, y):
        self.n_classes_ = len(set(y))
        self.n_features_ = X.shape[1]
        self.tree_ = self._grow_tree(X, y)

    def predict(self, X):
        return [self._predict(inputs) for inputs in X]

    def _best_split(self, X, y):
        m = y.size
        if m <= 1:
            return None, None
        num_parent = [np.sum(y == c) for c in range(self.n_classes_)]
        best_gini = 1.0 - sum((n / m) ** 2 for n in num_parent)
        best_idx, best_thr = None, None
        for idx in range(self.n_features_):
            thresholds, classes = zip(*sorted(zip(X[:, idx], y)))
            num_left = [0] * self.n_classes_
            num_right = num_parent.copy()
            for i in range(1, m):
                c = classes[i - 1]
                num_left[c] += 1
                num_right[c] -= 1
                gini_left = 1.0 - sum(
                    (num_left[x] / i) ** 2 for x in range(self.n_classes_)
                )
                gini_right = 1.0 - sum(
                    (num_right[x] / (m - i)) ** 2 for x in range(self.n_classes_)
                )
                gini = (i * gini_left + (m - i) * gini_right) / m
                if thresholds[i] == thresholds[i - 1]:
                    continue
                if gini < best_gini:
                    best_gini = gini
                    best_idx = idx
                    best_thr = (thresholds[i] + thresholds[i - 1]) / 2
        return best_idx, best_thr

    def _grow_tree(self, X, y, depth=0):
        num_samples_per_class = [np.sum(y == i) for i in range(self.n_classes_)]
        predicted_class = np.argmax(num_samples_per_class)
        node = Node(predicted_class=predicted_class)
        if depth < self.max_depth:
            idx, thr = self._best_split(X, y)
            if idx is not None:
                indices_left = X[:, idx] < thr
                X_left, y_left = X[indices_left], y[indices_left]
                X_right, y_right = X[~indices_left], y[~indices_left]
                node.feature_index = idx
                node.threshold = thr
                node.left = self._grow_tree(X_left, y_left, depth + 1)
                node.right = self._grow_tree(X_right, y_right, depth + 1)
        return node

    def _predict(self, inputs):
        node = self.tree_
        while node.left:
            if inputs[node.feature_index] < node.threshold:
                node = node.left
            else:
                node = node.right
        return node.predicted_class

In [36]:
X=test_df.iloc[:, 2:].to_numpy()

In [37]:
clf = DecisionTreeClassifier(max_depth=1)
clf.fit(X, y)

In [ ]:
clf.predict([[12,21,23,12,23,21,23,21,32,1,23,12,3,12,4,12,12,412,12,32,12,43,12,32,123,345,12,21,12,21,12,12,12,12,12,122,122,12,12,12,12,12,12,12,12,12,12,12,12,12]])

In [84]:
asd=df1.iloc[:,2:].values.tolist()

In [86]:
z = clf.predict(asd)
z

[0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 ...]

In [80]:
type([[12,21,23,12,23,21,23,21,32,1,23,12,3,12,4,12,12,412,12,32,12,43,12,32,123,345,12,21,12,21,12,12,12,12,12,122,122,12,12,12,12,12,12,12,12,12,12,12,12,12]])

list